config/routes.rb
Rails.application.routes.draw do
    devise_for :accounts
    resources :posts do
      member do
        patch :flag
      end
    end
    resources :categories
    
    root to: "public#home"
  match 'accounts/:id' => 'accounts#destroy', :via => :delete

  resources :accounts, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :account
  belongs_to :genre
  belongs_to :city
  belongs_to :instrument
  
  
  validates :contact, presence: true, length: { minimum: 5, maximum: 20 }
  validates :genre, presence: true
  validates :instrument, presence: true
  validates :city, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }
  
  validate  :clean_post

  def clean_post
    profanity_filter = LanguageFilter::Filter.new matchlist: :profanity
    sj = Swearjar.default

    if profanity_filter.match? title then
      errors.add(:title, "contains language violation.")
    end

    if profanity_filter.match? content then
      errors.add(:content, "contains language violation.")
    end

    profanity_filter = LanguageFilter::Filter.new matchlist: :hate
    if profanity_filter.match? title then
      errors.add(:title, "contains language violation.")
    end

    if profanity_filter.match? content then
      errors.add(:content, "contains language violation.")
    end

    profanity_filter = LanguageFilter::Filter.new matchlist: :sex
    if profanity_filter.match? title then
      errors.add(:title, "contains language violation.")
    end

    if profanity_filter.match? content then
      errors.add(:content, "contains language violation.")
    end

    
    if sj.profane?(:content) == true then
      errors.add(:content, "contains language violation.")
    end
  end

  

  

  #validate_language :content, matchlist: :profanity, matchlist: :hate, matchlist: :sex
  #validate_language :title, matchlist: :profanity, matchlist: :hate, matchlist: :sex
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
    
    @search = Post.ransack(params[:q])
    @posts = @search.result.order("created_at DESC").paginate(page: params[:page], :per_page => 5)

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    if @post.account != current_account
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if (@post.account != current_account) 
      return render plain: 'Not Allowed', status: :forbidden
    end

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def flag
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        if @post.flag == true
          format.html { redirect_to @post, notice: 'Post has been flagged.' }
          format.json { render :show, status: :ok, location: @post }
        elsif @post.flag == false
          format.html { redirect_to @post, notice: 'Flag has been removed.' }
          format.json { render :show, status: :ok, location: @post }
        end
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])

    if (@post.account != current_account) && (current_account.admin == false)
      return render plain: 'Not Allowed', status: :forbidden
    end

    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:title,:contact , :content, :category_id, :genre_id, :city_id, :instrument_id, :flag)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

  <% if post.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form">

    <div class="form-group" >
      <label> Contact by Phone/Email/Social media tag :</label>
      <input type="contact" class="form-control" id="<%= form.text_field :contact %>
      <small  class="form-text text-muted">Optional</small>    
    </div>

    <div class="row">
      <div class="col">
        <div class="form-group">
          <label>Posting as :</label>
          <select class="form-control" style="width:auto;" id=<%= form.select :category_id, Category.all.collect {|c| [ c.name, c.id ] },{:include_blank => true} %>
          </select>
        </div>

    
        <div class="form-group">
          <label>City :</label>
          <select class="form-control" style="width:auto;" id=<%= form.select :city_id, City.all.collect {|c| [ c.name, c.id ] },{:include_blank => true} %>
          </select>
        </div>
      </div>


      <div class="col">
        <div class="form-group">
          <label>Genre :</label>
          <select class="form-control" style="width:auto;" id=<%= form.select :genre_id, Genre.all.collect {|c| [ c.name, c.id ] },{:include_blank => true} %>
          </select>
        </div>
      

        <div class="form-group">
          <label>Instrument :</label>
          <select class="form-control" style="width:auto;" id=<%= form.select :instrument_id, Instrument.all.collect {|c| [ c.name, c.id ] },{:include_blank => true} %>
          </select>
        </div>
      </div>
    </div>

      <div class="form-group">
        <label> Title of Post :</label>
        <input type="title" class="form-control" id="<%= form.text_field :title %>
      </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea1">Post Description :</label>
      <textarea class="form-control" rows="3" id=<%= form.text_area :content %></textarea>
    </div>
    

    <br>
    <%= form.submit "Post", class: 'btn-primary custom-btn btn-block btn-lg' %>
    
    <br>   
  </form>

<% end %>
  
  

app/views/posts/edit.html.erb
<div class="card  bg-dark  text-light">
  <div class="card-body">

    <h1>Edit Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="card  bg-dark  text-light">
  <div class="card-body">

    <p id="notice"><%= notice %></p>

    <h1>Search Results</h1>
    <br>

    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

        <% @posts.each do |post| %>
          <div class="category-post">
            <span class="post-title"><%= link_to post.title, post_path(post) %></span>
            <span class="post-date"><%= time_ago_in_words post.created_at %></span>
            <br>
          </div>
        <% end %>

        
    </table>
    <%= will_paginate @posts %>
    <br>
  </div>
</div>

app/views/posts/new.html.erb
<div class="card  bg-dark  text-light">
  <div class="card-body">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
      <div class="card  bg-dark  text-light">
        <div class="card-body">

          <% if (current_account == @post.account)%>
            <%= link_to 'Edit Post', edit_post_path(@post)  ,class: 'btn btn-danger'%> |
            <%= link_to 'Delete Post', post_path(@post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'},class: 'btn btn-danger' %>
          <br>
          <% else %>

            <%= form_for @post, {:url => flag_post_path(@post), :method=>:patch} do |f| %>
              <%= f.hidden_field :flag, value: true %>
              <%= f.submit 'Flag Post as Inappropriate', class: 'btn btn-sm btn-warning' %>
            <% end %>
         
          <% end %>

          <br>
          <div class="container ">
            <div class="row ">
              
              <% if (current_account.admin == true ) %>
              
                <%= link_to 'Delete Post', post_path(@post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'},class: 'btn btn-danger mr-2' %>     
                <%= link_to 'Delete Account', account_path(@post.account), method: :delete, data: {confirm: 'Are you sure you want to delete your account? All of your posts will be removed as well.'},class: 'btn btn-danger mr-2' %>    
                <%= form_for @post, {:url => flag_post_path(@post), :method=>:patch} do |f| %>
                  <%= f.hidden_field :flag, value: false %>
                  <%= f.submit 'Remove Flag', class: 'btn  btn-warning ' %>
                <% end %>
              <% end %>
            </div>
          </div>

          <br>
   

          <span class="posted-id">Posted <%= time_ago_in_words @post.created_at %> ago </span>
            <br><br>

          <h1> <%= @post.title %></h1>
          <h5> City : <%= @post.city.name %></h5>
          <h5> Genre : <%= @post.genre.name %></h5>
          <h5> Looking for / Interesed in playing :  <%= @post.instrument.name %></h5>
            

          <br>

          <%= simple_format @post.content %>

          <br>

          <p> Contact info: <%= simple_format @post.contact %> </p>

          <br>

          <p class="post-meta">
            <span class="post-id">Post id: <%= @post.id.to_s %></span>
          </p>
        </div>
      </div>
    
</div>