config/routes.rb
Rails.application.routes.draw do
    devise_for :accounts
    resources :posts do
      member do
        patch :flag
      end
    end
    resources :categories
    
    root to: "public#home"
  match 'accounts/:id' => 'accounts#destroy', :via => :delete

  resources :accounts, only: :show
end

app/views/layouts/_breadcrumb_nav.html.erb
<nav class="navbar navbar-dark bg-dark text-center  ">  
  <div class="container">
  


    <nav class="navbar-brand nav">
      <% if @post.present? && !@post.new_record?
        category = @post.category %>
        <%= link_to "Home", root_path %> 
        >> <%= link_to category.name, category_path(category) %> >>
        <%= @post.title %>
      <% end %>

      <% if controller.controller_name == "public" %>
        <%= link_to "Welcome, Traveler.", root_path %> 
      <% end %>

      <% if controller.controller_name == "categories" %>
        <%= link_to "Home", root_path %> 
        >>  <%= render "categories/category_sidebar" %>
      <% end %>

      <% if controller.controller_name == "accounts" && account_signed_in? %>
        <%= link_to "Home", root_path %> 
        >>  <%=  'My Account' %>
      <% end %>

      <% if controller.controller_name == "accounts" && !account_signed_in? %>
        <%= link_to "Home", root_path %> 
        >>  <%=  'Sign In' %>
      <% end %>

      <% if @post.present? && @post.new_record?%>
        <%= link_to "Home", root_path %> 
        >>  <%=  'Create New Post' %>
      <% end %>

      <% if controller.controller_name == "posts" && !@post.present? %>
        <%= link_to "Home", root_path %> 
        >>  <%=  'Search Results' %>
      <% end %>  
    </nav>


    <h1 class="navbar-brand nav">
      <% if account_signed_in? %>
        <div class="row">
          <div class="col">
            <%= link_to "Sign Out", destroy_account_session_path, method: :delete%>
          </div>
          <div class="col">
            <%= link_to "My Account", account_path(current_account)  %> 
          </div>
       </div>
      <% else %>
        <div class="row">
          <div class="col">
            <%= link_to "Sign In", new_account_session_path %> 
          </div>
          <div class="col">
            <%= link_to "Sign Up", new_account_registration_path %> 
          </div>
        </div>
      <% end %>
    </h1> 

  </div>
</nav>
  
  
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mxtx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Asap&family=Rajdhani:wght@500&family=Raleway&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'master', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/breadcrumb_nav" %>

    </header>

    <% if notice.present? %>
      <br>
      <div class="row justify-content-center">
        <div class="alert alert-primary" role="alert">
          <p class="notice"><%= notice %></p>
        </div>
      </div>
    <% end %>

    <div class="main container">
      <div class="card  bg-dark main-left text-light">
        <div class="card-body">
          <p><%= link_to "MXTX", root_path %></p>

          <%= link_to "Create new post",new_post_path,class: 'btn-primary custom-btn btn-block btn-lg' %>

          <br>
          <br>

          <h2> Search Posts </h2>
          <%= search_form_for @search do |f| %>

          <div class="form">
            <div class="form-group">
              <label> Keyword :</label>
              <input type="keyword" class="form-control " id=<%= f.text_field :title_or_content_cont %> 
            </div>

            <div class="form-group">
              <label>Looking For :</label>
              <select class="form-control" style="width:auto;" id=<%= f.select :category_id_eq, Category.all.collect {|c| [ c.name, c.id ] },{:include_blank => 'Any'}%>
              </select>
            </div>


            <div class="form-group">
              <label>Genre :</label>
              <select class="form-control" style="width:auto;" id=<%= f.select :genre_id_eq, Genre.all.collect {|c| [ c.name, c.id ] },{:include_blank => 'Any'} %>
              </select>
            </div>

            <div class="form-group">
              <label>Instrument :</label>
              <select class="form-control" style="width:auto;" id=<%= f.select :instrument_id_eq, Instrument.all.collect {|c| [ c.name, c.id ] },{:include_blank => 'Any'} %>
              </select>
            </div>
            
            <div class="form-group">
              <label>City :</label>
              <select class="form-control" style="width:auto;" id=<%= f.select :city_id_eq, City.all.collect {|c| [ c.name, c.id ] },{:include_blank => 'Any'} %>
              </select>
            </div>

            <br>
            <%= f.submit "Search",class: 'btn-primary custom-btn btn-block btn-lg' %>
            <% end %>

          </div>
          <br>
        </div>
        <br>
      </div>

      <div class="main-right">
        <%= yield %>
      </div>
    </div>
  </body>
</html>